apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenweb
  namespace: deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maven
  template:
    metadata:
      labels:
        app: maven
    spec:
      containers:
      - name: mavenwebapp
        image: shahir5890/mavenk8:TAG 
        ports:
        - containerPort: 9090
        resources:
          limits:
            cpu: 500m
            memory: 556Mi
          requests:
            cpu: 200m
            memory: 200Mi
        livenessProbe:
          httpGet:
            path: /maven-web-application
            port: 9090
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /maven-web-application
            port: 9090
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: mavensvc
  namespace: deployment
spec:
  type: NodePort
  selector:
    app: maven
  ports:
  - port: 80
    targetPort: 9090
    nodePort: 30000
