apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mithunweb
  namespace: test-ns
spec:
  rules:
  - host: "mithuntech.com"
    http:
      paths:
      - pathType: Prefix
        path: "/maven-web-application"
        backend:
          service:
            name: mavenwebappsvc
            port:
              number: 80
